version: "3"

services:
  ermis-login:
    container_name: ermis-login
    build:
      context: .
    restart: always
    ports:
      - "5005:8080"
    environment:
      EM_DB_HOST: caduceus
      EM_DB_PORT: 5432
      EM_DB_USER: ermis
      EM_DB_PASSWORD: ermis
      EM_DB_NAME: ermis
      EM_LOG_LEVEL: debug
      EM_CLIENT_ORIGIN_URL: http://localhost:8000
      EM_CLIENT_SECRET: 9f84c0001c10db502884ca678a6001a45c16662e96ca549df08993465cb50b5c

  caduceus:
    container_name: caduceus
    image: postgres:15.1-alpine3.17
    restart: always
    environment:
      POSTGRES_DB: ermis
      POSTGRES_USER: ermis
      POSTGRES_PASSWORD: ermis
    volumes:
      - ./db_dev:/var/lib/postgresql/data
